### General settings
nnsvs_root:               "../nnsvs"
## Singer's name
spk:                      english_speaker
## exp tag(for managing experiments)
tag:                      enunu_training_kit

## Output directory
# All the generated labels, intermediate files, and segmented wav files
# will be saved in the following directory
out_dir:                  data

## Songs to be excluded from trainig.
exclude_songs:            []

## Lyric -> Phonemes table
## HTS-style question used for extracting musical/linguistic context from musicxml files
table_path:               dic/blank.table
question_path:            hed/DynamiVox_English_NNSVS.hed

# Audio sampling rate
# [CAUTION] Changing sample_rate may affect the dimension number of acoustic features.
# DO NOT CHANGE this unless you know the relationship between the dim of bap and sample_rate.
sample_rate:              44100


###########################################################
#          DATA PREPARATION SETTING    (STAGE 0)          #
###########################################################
stage0:
    ## Directory of unzipped singing voice database
    db_root:              ../singing_database
    ### How to segment LAB and WAV before training
    # Changing this config might help you avoid "SegmentationFault" on stage 1.
    # Choices are [null, long, middle, short] (middle is recommended)
    # If "never",  LAB is not devided.
    # If "long",   LAB is devided at "pau"-"pau" or "pau""-"sil phoneme pattern.
    # If "middle", LAB is devided at the start of each <middle_frequency> "pau"s.
    # If "short",  LAB is devided at the start of each "pau" phoneme.
    segmentation_mode:    middle
    middle_frequency:     3

    # Choices are [strict, middle, lenient]
    vowel_duration_check: middle

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

timelag_features:         defaults
duration_features:        defaults
acoustic_features:        static_deltadelta

###########################################################
#                TRAINING SETTING                         #
###########################################################

# Models
# To customize, put your config or change ones in
# conf/train/{timelag,duration,acoustic}/ and
# specify the config name below
# NOTE: *_model: model definition, *_train: general train configs,
# *_data:                 data configs (e.g., batch size)

timelag_model:            timelag_ffn
timelag_train:            myconfig
timelag_data:             myconfig

duration_model:           duration_lstm
duration_train:           myconfig
duration_data:            myconfig

acoustic_model:           acoustic_conv
acoustic_train:           myconfig
acoustic_data:            myconfig

# Pretrained model dir (leave empty to disable)
# pretrained_expdir:      exp/unnamed_enunu_training_kit
pretrained_expdir:

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################
timelag_synthesis:        defaults
duration_synthesis:       defaults
acoustic_synthesis:       defaults

# latest.pth or best.pth
timelag_eval_checkpoint:  best_loss.pth
duration_eval_checkpoint: best_loss.pth
acoustic_eval_checkpoint: best_loss.pth
